version: '2'
services:
  ui:
    build: ./ui
    environment:
     - REPOSITORY_ADDR=repository:50051
    ports:
     - "3000:3000"
  repository:
    build:
      context: ./backend
      dockerfile: ./repositories/service/Dockerfile
    depends_on:
     - redis
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
     - ./backend/volumes:/data
