version: '2'
services:
  repository:
    build:
      context: ./backend
      dockerfile: ./repositories/service/Dockerfile
    ports:
     - "50051:50051"
    depends_on:
     - redis
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
     - ./backend/volumes:/data
